// Archivo: data-jovenes.js
// Mazo: Jóvenes en el Mundo - 72 reflexiones para la juventud de hoy.

const CARTAS_JOVENES = [
    { id: "juv-01", q: "«Todos nacemos como originales, pero muchos mueren como fotocopias.»\n\n¿En qué partes de tu vida sentís que estás actuando para encajar en el molde de otros en lugar de ser quien Dios te llamó a ser?", a: "Beato Carlo Acutis" },
    { id: "juv-02", q: "«¡No tengan miedo de ser los santos del nuevo milenio!»\n\n¿Qué es eso 'políticamente correcto' que te da miedo cuestionar por temor a ser cancelado o burlado por tus amigos?", a: "San Juan Pablo II" },
    { id: "juv-03", q: "«Hacia lo alto.»\n\n¿Te estás conformando con una vida mediocre de 'pantalla y sillón' o sentís el llamado a escalar metas que realmente valgan la pena?", a: "Beato Pier Giorgio Frassati" },
    { id: "juv-04", q: "«La santidad consiste en estar siempre alegres.»\n\n¿Tu alegría depende de los 'likes' y la aprobación externa, o nace de una paz interior que nadie te puede quitar?", a: "San Juan Bosco" },
    { id: "juv-05", q: "«Cristo vive y te quiere vivo.»\n\n¿En qué áreas de tu vida te sentís 'muerto' o anestesiado (vicios, apatía, falta de sueños) y necesitás que Jesús te despierte?", a: "Papa Francisco" },
    { id: "juv-06", q: "«Yo no tengo miedo; para esto nací.»\n\nSi supieras que Dios te respalda totalmente, ¿qué gran paso te animarías a dar mañana mismo?", a: "Santa Juana de Arco" },
    { id: "juv-07", q: "«Sean custodios de la belleza.»\n\n¿Qué contenido estás consumiendo en tus redes: algo que eleva tu espíritu o algo que te deja vacío y comparándote con los demás?", a: "Papa Benedicto XVI" },
    { id: "juv-08", q: "«Si eres lo que deberías ser, prenderás fuego al mundo.»\n\n¿Estás usando tus talentos para brillar vos solo/a, o para iluminar la vida de los que están en la oscuridad?", a: "Santa Catalina de Siena" },
    { id: "juv-09", q: "«Hagan lío.»\n\n¿Tu fe es algo 'guardado' y privado, o te animás a incomodar con tu testimonio de honestidad y servicio en tu lugar de estudio?", a: "Papa Francisco" },
    { id: "juv-10", q: "«La medida del amor es amar sin medida.»\n\n¿Estás amando a los demás solo cuando te conviene, o sos capaz de sacrificarte un poco por un amigo que la está pasando mal?", a: "San Bernardo" },
    { id: "juv-11", q: "«Nada está perdido si se tiene el valor de empezar de nuevo.»\n\n¿Qué error del pasado te está frenando para creer que hoy podés tener un nuevo comienzo con Dios?", a: "San Juan XXIII" },
    { id: "juv-12", q: "«La pureza del corazón es ver a Dios en todo.»\n\n¿Cómo influye lo que ves y escuchás en tu forma de tratar y valorar a las personas del sexo opuesto?", a: "San Agustín" },
    { id: "juv-13", q: "«Dios no nos llama para ser exitosos, sino para ser fieles.»\n\n¿Tu valor personal lo medís por tus logros académicos/deportivos o por la calidad de tu corazón?", a: "Santa Teresa de Calcuta" },
    { id: "juv-14", q: "«Prefiero morir antes que pecar.»\n\n¿Tenés claros cuáles son tus 'límites innegociables' o te dejas arrastrar por lo que hace la mayoría en las fiestas?", a: "Santo Domingo Savio" },
    { id: "juv-15", q: "«Ustedes son la sal de la tierra.»\n\n¿Tu presencia en tu grupo de amigos hace que las conversaciones sean mejores, o te sumás al chisme y a la crítica de siempre?", a: "Mateo 5, 13" },
    { id: "juv-16", q: "«Acuérdate de tu Creador en los días de tu juventud.»\n\n¿Estás dejando a Dios para 'cuando sea viejo', perdiéndote la aventura de caminar con Él ahora que tenés toda la energía?", a: "Eclesiastés 12, 1" },
    { id: "juv-17", q: "«Nadie tiene mayor amor que el que da la vida.»\n\n¿Estás dispuesto/a a dejar el celular un rato para escuchar de verdad a alguien que necesita desahogarse?", a: "Juan 15, 13" },
    { id: "juv-18", q: "«El amor echa fuera el temor.»\n\n¿Qué miedo te está impidiendo ser auténtico/a y decir lo que realmente pensás y creés?", a: "1 Juan 4, 18" },
    { id: "juv-19", q: "«Busquen primero el Reino de Dios.»\n\n¿Tus prioridades de hoy reflejan lo que querés ser en 10 años, o solo estás viviendo para el placer del momento?", a: "Mateo 6, 33" },
    { id: "juv-20", q: "«Donde está tu tesoro, allí estará tu corazón.»\n\nSi miramos tu historial de búsqueda o tus gastos, ¿qué dirían que es lo más importante en tu vida hoy?", a: "Lucas 12, 34" },
    { id: "juv-21", q: "«La verdad los hará libres.»\n\n¿Cuántas mentiras o 'medias verdades' estás sosteniendo para mantener una imagen que no es la real?", a: "Juan 8, 32" },
    { id: "juv-22", q: "«Sean testigos de la esperanza.»\n\nFrente al pesimismo de tus compañeros sobre el país o el futuro, ¿aportás una mirada de fe o te sumás a la queja?", a: "San Juan Pablo II" },
    { id: "juv-23", q: "«Corran de tal manera que ganen el premio.»\n\n¿Estás entrenando tu voluntad con pequeños sacrificios diarios, o sos esclavo/a de tus ganas de cada momento?", a: "1 Corintios 9, 24" },
    { id: "juv-24", q: "«Habla, Señor, que tu siervo escucha.»\n\n¿Hacés aunque sea 5 minutos de silencio real al día para dejar que Dios te dé una idea o un consejo?", a: "1 Samuel 3, 9" },
    { id: "juv-25", q: "«Ustedes son la luz del mundo.»\n\n¿Te animás a prender la luz de la honestidad cuando ves que todos están haciendo trampa en algo?", a: "Mateo 5, 14" },
    { id: "juv-26", q: "«El que no sirve para servir, no sirve para vivir.»\n\n¿En qué proyecto solidario o ayuda en la Capilla podrías poner tu energía joven este mes?", a: "Papa Francisco" },
    { id: "juv-27", q: "«Permanezcan en mi amor.»\n\n¿Buscás a Dios solo cuando tenés un examen o un problema, o querés ser Su amigo/a todos los días?", a: "Juan 15, 9" },
    { id: "juv-28", q: "«No dejes que nadie te menosprecie por ser joven.»\n\n¿Te usás a vos mismo/a la excusa de 'soy chico' para no comprometerte en serio con tu fe?", a: "1 Timoteo 4, 12" },
    { id: "juv-29", q: "«El que quiera ser el primero, que sea el servidor de todos.»\n\n¿Buscás destacar y tener poder sobre los demás, o buscás cómo hacerles la vida más fácil?", a: "Marcos 9, 35" },
    { id: "juv-30", q: "«Dime con quién andas y te diré quién eres.»\n\n¿Tus amigos actuales te impulsan a ser una mejor versión de vos mismo/a, o te hunden en la mediocridad?", a: "Sabiduría Popular" },
    { id: "juv-31", q: "«Si Dios está con nosotros, ¿quién contra nosotros?»\n\n¿Por qué te paraliza tanto el qué dirán de personas que ni siquiera conocen tu corazón?", a: "Romanos 8, 31" },
    { id: "juv-32", q: "«Hágase en mí según tu palabra.»\n\n¿Estás dispuesto/a a decirle que sí a Dios aunque el plan que Él tiene sea diferente al que vos soñaste?", a: "Virgen María" },
    { id: "juv-33", q: "«Pedid y se os dará.»\n\n¿Estás pidiendo cosas materiales o estás pidiendo sabiduría para saber qué hacer con tu vida?", a: "Mateo 7, 7" },
    { id: "juv-34", q: "«Ustedes son mis amigos.»\n\n¿Tratás a Jesús como alguien que vive en un libro de historia o como alguien que camina al lado tuyo en la facultad/colegio?", a: "Juan 15, 14" },
    { id: "juv-35", q: "«La fe sin obras está muerta.»\n\n¿De qué sirve decir que creés si tus acciones en la calle o con tu familia dicen lo contrario?", a: "Santiago 2, 17" },
    { id: "juv-36", q: "«Examínenlo todo y quédense con lo bueno.»\n\n¿Sos capaz de filtrar críticamente lo que ves en redes o te tragás todo lo que el algoritmo te tira?", a: "1 Tesalonicenses 5, 21" },
    { id: "juv-37", q: "«Vengan a mí los que están cansados.»\n\n¿Dónde buscás descanso para tu mente cuando el estrés de los estudios te supera?", a: "Mateo 11, 28" },
    { id: "juv-38", q: "«Miren que yo hago nuevas todas las cosas.»\n\n¿Creés que tus vicios o malos hábitos son parte de tu identidad y no podés cambiar, o confiás en el poder de Dios?", a: "Apocalipsis 21, 5" },
    { id: "juv-39", q: "«Ustedes son el ahora de Dios.»\n\n¿Estás esperando a ser 'adulto' para empezar a hacer el bien, o te das cuenta de que el mundo te necesita hoy?", a: "Papa Francisco" },
    { id: "juv-40", q: "«El amor no pasa nunca.»\n\nEn un mundo de relaciones descartables y efímeras, ¿te animás a apostar por un amor fiel y duradero?", a: "1 Corintios 13, 8" },
    { id: "juv-41", q: "«Te basta mi gracia.»\n\n¿Estás obsesionado/a con tus complejos físicos o debilidades, olvidando que Dios te ama exactamente como sos?", a: "2 Corintios 12, 9" },
    { id: "juv-42", q: "«Entren por la puerta estrecha.»\n\n¿Elegís el camino fácil que todos siguen aunque termine mal, o tenés el coraje de ir a contracorriente?", a: "Mateo 7, 13" },
    { id: "juv-43", q: "«Señor, ¿a quién iremos?»\n\n¿Hay algo en este mundo que te haya dado la paz que sentís cuando estás cerca de Dios?", a: "Juan 6, 68" },
    { id: "juv-44", q: "«No se cansen de hacer el bien.»\n\n¿Te desanimás rápido cuando no ves resultados inmediatos en tus esfuerzos espirituales?", a: "Gálatas 6, 9" },
    { id: "juv-45", q: "«Bienaventurados los limpios de corazón.»\n\n¿Cómo estás cuidando tu mirada y tus pensamientos en la intimidad de tu habitación?", a: "Mateo 5, 8" },
    { id: "juv-46", q: "«Yo soy el pan de vida.»\n\n¿Estás alimentando tu mente con chismes y odio, o con la paz de la Eucaristía?", a: "Juan 6, 35" },
    { id: "juv-47", q: "«Vayan y hagan discípulos.»\n\n¿Te animás a invitar a un amigo a la Capilla o te da vergüenza que sepan que sos cristiano/a?", a: "Mateo 28, 19" },
    { id: "juv-48", q: "«Padre, perdónalos.»\n\n¿Estás guardando un rencor que te está envenenando por dentro por algo que te hicieron hace tiempo?", a: "Lucas 23, 34" },
    { id: "juv-49", q: "«El Espíritu Santo les enseñará todo.»\n\n¿Le pedís luz al Espíritu antes de tomar una decisión importante sobre tu carrera o tu pareja?", a: "Juan 14, 26" },
    { id: "juv-50", q: "«El Reino de Dios está dentro de ustedes.»\n\n¿Buscás la felicidad afuera (fiestas, compras, fama) o cultivás tu vida interior?", a: "Lucas 17, 21" },
    { id: "juv-51", q: "«Ustedes son mis testigos.»\n\n¿Tu estilo de vida hace que los demás se pregunten por qué sos diferente y tenés tanta paz?", a: "Hechos 1, 8" },
    { id: "juv-52", q: "«Si el grano de trigo no muere...»\n\n¿A qué egoísmo o capricho personal necesitás 'morir' hoy para que algo bueno crezca en tu familia?", a: "Juan 12, 24" },
    { id: "juv-53", q: "«Den gratis lo que recibieron gratis.»\n\n¿Estás usando tu inteligencia y juventud para lucrar solamente o para servir a los que menos tienen?", a: "Mateo 10, 8" },
    { id: "juv-54", q: "«Vengan y lo verán.»\n\n¿Estás dispuesto/a a tener una experiencia real con Jesús o te quedás con lo que te contaron otros?", a: "Juan 1, 39" },
    { id: "juv-55", q: "«No tengan miedo de los que matan el cuerpo.»\n\n¿Te preocupa más tu imagen física que la salud de tu alma?", a: "Mateo 10, 28" },
    { id: "juv-56", q: "«El que me sigue no caminará en tinieblas.»\n\n¿Sentís que tu vida no tiene rumbo? ¿Y si probás seguir el mapa del Evangelio?", a: "Juan 8, 12" },
    { id: "juv-57", q: "«Sean santos, porque yo soy santo.»\n\n¿Creés que la santidad es para viejitos o entendés que es ser la mejor versión de vos mismo/a hoy?", a: "1 Pedro 1, 16" },
    { id: "juv-58", q: "«Tú tienes palabras de vida eterna.»\n\n¿En qué libros o influencers estás buscando las respuestas a tus preguntas más profundas?", a: "Juan 6, 68" },
    { id: "juv-59", q: "«El amor es paciente, es servicial.»\n\n¿Cómo está tu paciencia con tus padres o hermanos en el día a día?", a: "1 Corintios 13" },
    { id: "juv-60", q: "«Confíen, yo he vencido al mundo.»\n\n¿Te angustia el caos del mundo o confiás en que Dios tiene la última palabra?", a: "Juan 16, 33" },
    { id: "juv-61", q: "«El que pide, recibe.»\n\n¿Hace cuánto que no le pedís a Dios algo con la fe de un niño que sabe que su Padre lo escucha?", a: "Mateo 7, 8" },
    { id: "juv-62", q: "«Levántate y anda.»\n\n¿En qué situación de fracaso te quedaste sentado/a lamentándote en lugar de volver a empezar?", a: "Mateo 9, 5" },
    { id: "juv-63", q: "«Ustedes son el templo de Dios.»\n\n¿Cómo estás cuidando tu cuerpo y tu salud? ¿Le das el valor sagrado que tiene?", a: "1 Corintios 3, 16" },
    { id: "juv-64", q: "«No amen al mundo ni las cosas del mundo.»\n\n¿Estás dejando que las modas pasajeras dicten tus valores profundos?", a: "1 Juan 2, 15" },
    { id: "juv-65", q: "«Pidan sabiduría y se les dará.»\n\nFrente a esa duda que tenés hoy, ¿ya le preguntaste a Dios qué es lo mejor para tu alma?", a: "Santiago 1, 5" },
    { id: "juv-66", q: "«Bienaventurados los que trabajan por la paz.»\n\nEn tus grupos de WhatsApp, ¿sos el que calma los ánimos o el que agita las peleas?", a: "Mateo 5, 9" },
    { id: "juv-67", q: "«Yo soy el Buen Pastor.»\n\n¿Te sentís perdido/a en la multitud? ¿Podés sentir que Él te llama por tu nombre hoy?", a: "Juan 10, 11" },
    { id: "juv-68", q: "«Todo es posible para el que cree.»\n\n¿Cuál es ese 'imposible' en tu vida que necesitás poner en manos de Dios hoy?", a: "Marcos 9, 23" },
    { id: "juv-69", q: "«Miren cómo se aman.»\n\n¿Tu grupo de jóvenes en la Capilla es un lugar de amor real o de competencia y grupos cerrados?", a: "Primeros Cristianos" },
    { id: "juv-70", q: "«Permanezcan firmes en la fe.»\n\n¿Tu fe se tambalea con cualquier video de TikTok que la cuestiona, o tenés raíces profundas?", a: "1 Corintios 16, 13" },
    { id: "juv-71", q: "«Den gloria a Dios con su cuerpo.»\n\n¿Sos consciente del valor inmenso de tu sexualidad y tu afectividad como dones de Dios?", a: "1 Corintios 6, 20" },
    { id: "juv-72", q: "«Estaré con ustedes siempre.»\n\nSi hoy fuera un día difícil, ¿podrías descansar en la certeza de que Jesús camina al lado tuyo?", a: "Mateo 28, 20" }
];

const PALABRAS_FONDO = [
    'IDENTIDAD', 'TESTIGO', 'JUVENTUD', 'LUZ', 'PROPÓSITO', 
    'FUEGO', 'VALENTÍA', 'SUEÑOS', 'AMISTAD', 'CAMINO', 'VERDAD', 'VIDA'
];