// Índice de búsqueda sitewide para la sección "Profundizá"
const SEARCH_INDEX = [
    // Hub principal
    { title: "Profundizá tu Fe", desc: "Portal con todas las herramientas interactivas para aprender, jugar y reflexionar.", cat: "Portal", url: "index.html", icon: "fa-book-open" },

    // Catequesis y conocimiento
    { title: "¿Sabías que...?", desc: "Datos curiosos, historia y misterios ocultos de nuestra fe católica.", cat: "Catequesis", url: "sabiasque.html", icon: "fa-lightbulb" },
    { title: "Calendario Litúrgico", desc: "Tiempos, colores litúrgicos y fiestas importantes del año.", cat: "Catequesis", url: "calendario.html", icon: "fa-calendar-alt" },
    { title: "Glosario de la Fe", desc: "Diccionario simple y amigable de términos de la Iglesia.", cat: "Catequesis", url: "glosario.html", icon: "fa-book" },
    { title: "La Santa Misa", desc: "El misterio, los símbolos y el silencio de la Liturgia.", cat: "Catequesis", url: "misas.html", icon: "fa-church" },
    { title: "Vivir la Liturgia", desc: "Un recorrido por los 7 Sacramentos.", cat: "Catequesis", url: "vivirliturgia.html", icon: "fa-ring" },
    { title: "Vidas que Inspiran", desc: "Encuentros con los Santos y personas que dejaron huella.", cat: "Catequesis", url: "vidas.html", icon: "fa-dove" },

    // Oración y espiritualidad
    { title: "Conecta con Dios", desc: "Reflexiones y guías prácticas para mejorar tu oración.", cat: "Oración", url: "conecta.html", icon: "fa-plug" },
    { title: "Diario de Gratitud", desc: "Espacio personal para agradecer a Dios y guardar bendiciones.", cat: "Oración", url: "gratitud.html", icon: "fa-praying-hands" },
    { title: "Botiquín Espiritual / Santoral", desc: "Buscá el intercesor y la oración indicada para tu necesidad.", cat: "Oración", url: "santoral.html", icon: "fa-briefcase-medical" },

    // Dinámicas y reflexión
    { title: "Mazos de Reflexión", desc: "Sacá una carta al azar con pasajes bíblicos y reflexiones.", cat: "Dinámicas", url: "mazos.html", icon: "fa-layer-group" },
    { title: "Desafíos por Edades (Quizzes)", desc: "Trivias para niños, adolescentes y adultos.", cat: "Dinámicas", url: "quiz.html", icon: "fa-clipboard-question" },
    { title: "Luz para el Alma", desc: "Frases de inspiración cristiana, bíblica o de los santos.", cat: "Dinámicas", url: "frases.html", icon: "fa-lightbulb" },

    // 12 mazos
    { title: "Mazo: Niños (4 a 6)", desc: "Semillitas de amor para hablar de Jesús con los más chicos.", cat: "Mazo de cartas", url: "nenes4-6.html", icon: "fa-child-reaching" },
    { title: "Mazo: Creciendo (6 a 8)", desc: "Preguntas y juegos para descubrir el camino de la fe.", cat: "Mazo de cartas", url: "creciendo.html", icon: "fa-seedling" },
    { title: "Mazo: Jóvenes", desc: "Identidad, propósito y luz para la juventud de hoy.", cat: "Mazo de cartas", url: "jovenes.html", icon: "fa-bolt" },
    { title: "Mazo: Catequesis", desc: "Formación profunda para entender y amar las raíces de la fe.", cat: "Mazo de cartas", url: "catequesis.html", icon: "fa-book-bible" },
    { title: "Mazo: 1° Comunión", desc: "Preparando el corazón para recibir el Pan de Vida.", cat: "Mazo de cartas", url: "comunion.html", icon: "fa-wheat-awn" },
    { title: "Mazo: Confirmación", desc: "Los dones del Espíritu Santo para ser testigos valientes.", cat: "Mazo de cartas", url: "confirmacion.html", icon: "fa-fire-flame-curved" },
    { title: "Mazo: Matrimonio", desc: "Amor, unidad y paciencia para fortalecer la pareja.", cat: "Mazo de cartas", url: "matrimonio.html", icon: "fa-ring" },
    { title: "Mazo: Abrazo de Dios", desc: "Palabras de consuelo para momentos de tristeza y dolor.", cat: "Mazo de cartas", url: "abrazo.html", icon: "fa-hands-holding-child" },
    { title: "Mazo: Sabiduría", desc: "El legado de los Santos para iluminar decisiones diarias.", cat: "Mazo de cartas", url: "sabiduria.html", icon: "fa-feather-pointed" },
    { title: "Mazo: Servidores", desc: "Aliento y humildad para quienes sirven en la Capilla.", cat: "Mazo de cartas", url: "servidores.html", icon: "fa-hands-praying" },
    { title: "Mazo: Hermana Tierra", desc: "Reflexiones sobre el cuidado de la creación y la casa común.", cat: "Mazo de cartas", url: "ecologia.html", icon: "fa-leaf" },
    { title: "Mazo: Trascendencia", desc: "Mirar hacia lo eterno: la esperanza del cielo.", cat: "Mazo de cartas", url: "trascendencia.html", icon: "fa-infinity" },

    // 12 sabías que
    { title: "Sabías que: Antiguo Testamento", desc: "Adán, el Arca, Moisés y los grandes profetas.", cat: "Sabías que", url: "sq-antiguo.html", icon: "fa-scroll" },
    { title: "Sabías que: Nuevo Testamento", desc: "La vida oculta de Jesús, sus apóstoles y los Evangelios.", cat: "Sabías que", url: "sq-nuevo.html", icon: "fa-book-bible" },
    { title: "Sabías que: Misterios de la Misa", desc: "El significado de los colores, gestos y el altar.", cat: "Sabías que", url: "sq-misa.html", icon: "fa-church" },
    { title: "Sabías que: Sucesores de Pedro", desc: "Secretos del Vaticano, cónclaves y los Papas.", cat: "Sabías que", url: "sq-papas.html", icon: "fa-cross" },
    { title: "Sabías que: Ciencia y Fe", desc: "El Big Bang, curas científicos y la razón que abraza a Dios.", cat: "Sabías que", url: "sq-ciencia.html", icon: "fa-microscope" },
    { title: "Sabías que: La Virgen y los Santos", desc: "Historias de valentía y la patrona Santa Ana.", cat: "Sabías que", url: "sq-santos.html", icon: "fa-star" },
    { title: "Sabías que: Los Sacramentos", desc: "Los 7 canales invisibles de la Gracia.", cat: "Sabías que", url: "sq-sacramentos.html", icon: "fa-droplet" },
    { title: "Sabías que: Palabras con Alma", desc: "¿Qué significa Amén, Aleluya, Iglesia o Biblia?", cat: "Sabías que", url: "sq-palabras.html", icon: "fa-comment-dots" },
    { title: "Sabías que: Arte y Arquitectura", desc: "El lenguaje oculto en catedrales, vitrales y pinturas.", cat: "Sabías que", url: "sq-arte.html", icon: "fa-paint-brush" },
    { title: "Sabías que: Geografía de la Fe", desc: "Los lugares que pisó Jesús y los santuarios del mundo.", cat: "Sabías que", url: "sq-geografia.html", icon: "fa-map-marked-alt" },
    { title: "Sabías que: Milagros y Signos", desc: "Sucesos eucarísticos, curaciones y fenómenos que desafían la lógica.", cat: "Sabías que", url: "q-milagros.html", icon: "fa-star-of-life" },
    { title: "Sabías que: Nuestras Tradiciones", desc: "El origen del pesebre, el rosario, las procesiones.", cat: "Sabías que", url: "sq-tradiciones.html", icon: "fa-hands-praying" },

    // 6 quizzes
    { title: "Quiz: Descubriendo a Jesús (6 a 7 años)", desc: "Preguntas simples sobre quién creó el mundo y la vida de Jesús.", cat: "Quiz", url: "quiz-6-7.html", icon: "fa-sun" },
    { title: "Quiz: Camino a la Comunión (8 a 9 años)", desc: "La Misa, el Bautismo y los amigos de Dios en la Biblia.", cat: "Quiz", url: "quiz-8-9.html", icon: "fa-bread-slice" },
    { title: "Quiz: Aventura Bíblica (10 a 11 años)", desc: "La historia de la Salvación, mandamientos y profetas.", cat: "Quiz", url: "quiz-10-11.html", icon: "fa-map-marked-alt" },
    { title: "Quiz: Confirmando la Fe (12 a 15 años)", desc: "Dudas comunes, sacramentos y pertenencia.", cat: "Quiz", url: "quiz-12-15.html", icon: "fa-fire" },
    { title: "Quiz: Pensamiento Joven (16 a 18 años)", desc: "Apologética, defensa de la fe y grandes preguntas.", cat: "Quiz", url: "quiz-16-18.html", icon: "fa-shield-alt" },
    { title: "Quiz: Alta Teología (+18 años)", desc: "Desafíos teológicos para adultos.", cat: "Quiz", url: "quiz-18.html", icon: "fa-graduation-cap" },

    // 154 términos del Glosario de la Fe
    { title: "Abba", desc: "Palabra aramea que significa 'Papá' o 'Papi'. Así llamaba Jesús a Dios, enseñándonos que no es un jefe distan…", cat: "Glosario", url: "glosario.html#abba", icon: "fa-book-bible" },
    { title: "Absolución", desc: "Es el momento en el sacramento de la Confesión donde el sacerdote, actuando en nombre de Dios, perdona tus pe…", cat: "Glosario", url: "glosario.html#absolucion", icon: "fa-church" },
    { title: "Adoración", desc: "Reconocer a Dios como Creador y Señor absoluto de todo. Es un acto de amor y respeto profundo que se le debe…", cat: "Glosario", url: "glosario.html#adoracion", icon: "fa-praying-hands" },
    { title: "Adviento", desc: "Del latín 'venida'. Es el tiempo litúrgico de 4 semanas que precede a la Navidad. Un tiempo de espera alegre…", cat: "Glosario", url: "glosario.html#adviento", icon: "fa-church" },
    { title: "Alba", desc: "Túnica blanca larga que el sacerdote usa sobre su ropa para celebrar la Misa. Simboliza la pureza que el cris…", cat: "Glosario", url: "glosario.html#alba", icon: "fa-church" },
    { title: "Aleluya", desc: "Palabra de origen hebreo que significa 'Alaben a Dios'. Es un grito de alegría y alabanza muy utilizado en la…", cat: "Glosario", url: "glosario.html#aleluya", icon: "fa-church" },
    { title: "Altar", desc: "La mesa sagrada donde se celebra la Misa. Representa a Cristo mismo y a la mesa de la Última Cena donde Jesús…", cat: "Glosario", url: "glosario.html#altar", icon: "fa-church" },
    { title: "Ambón", desc: "Es el 'atril' o lugar elevado en el presbiterio desde donde se proclaman las lecturas de la Biblia durante la…", cat: "Glosario", url: "glosario.html#ambon", icon: "fa-church" },
    { title: "Amén", desc: "Palabra hebrea que significa 'Así sea' o 'Es verdad'. Al decir Amén al final de una oración o al comulgar, es…", cat: "Glosario", url: "glosario.html#amen", icon: "fa-praying-hands" },
    { title: "Amito", desc: "Lienzo blanco que el sacerdote coloca sobre sus hombros antes del alba. Simboliza la protección espiritual co…", cat: "Glosario", url: "glosario.html#amito", icon: "fa-church" },
    { title: "Ángeles", desc: "Seres espirituales creados por Dios, sin cuerpo físico, que actúan como sus mensajeros, protectores (como nue…", cat: "Glosario", url: "glosario.html#angeles", icon: "fa-cross" },
    { title: "Ángelus", desc: "Oración tradicional que se reza al mediodía para recordar el hermoso momento en que el Ángel le anunció a Mar…", cat: "Glosario", url: "glosario.html#angelus", icon: "fa-praying-hands" },
    { title: "Apóstol", desc: "Significa 'enviado'. Son los 12 hombres que Jesús eligió personalmente para que fueran sus testigos más cerca…", cat: "Glosario", url: "glosario.html#apostol", icon: "fa-book-bible" },
    { title: "Ascensión", desc: "El momento, 40 días después de resucitar, en que Jesús sube al Cielo en cuerpo y alma por su propio poder par…", cat: "Glosario", url: "glosario.html#ascension", icon: "fa-cross" },
    { title: "Asunción", desc: "El dogma que enseña que la Virgen María, al terminar su vida en la tierra, fue llevada al Cielo en cuerpo y a…", cat: "Glosario", url: "glosario.html#asuncion", icon: "fa-cross" },
    { title: "Ayuno", desc: "Práctica de privarse de comida o de otras cosas que nos gustan para fortalecer la voluntad y acercarnos más a…", cat: "Glosario", url: "glosario.html#ayuno", icon: "fa-praying-hands" },
    { title: "Bautismo", desc: "El primer sacramento y la puerta de entrada a la Iglesia. Nos limpia del pecado original y nos convierte ofic…", cat: "Glosario", url: "glosario.html#bautismo", icon: "fa-church" },
    { title: "Biblia", desc: "Conjunto de 73 libros sagrados inspirados por Dios. Se divide en Antiguo Testamento (antes de Jesús) y Nuevo…", cat: "Glosario", url: "glosario.html#biblia", icon: "fa-book-bible" },
    { title: "Bienaventuranzas", desc: "El 'mapa de la felicidad' que Jesús nos regaló en el Sermón del Monte. Son actitudes para vivir como verdader…", cat: "Glosario", url: "glosario.html#bienaventuranzas", icon: "fa-book-bible" },
    { title: "Blasfemia", desc: "Cualquier palabra, insulto o falta de respeto grave dirigida intencionalmente contra Dios, la Virgen María, l…", cat: "Glosario", url: "glosario.html#blasfemia", icon: "fa-cross" },
    { title: "Cáliz", desc: "La copa sagrada, generalmente de metal precioso, que usa el sacerdote en la Misa para poner el vino que luego…", cat: "Glosario", url: "glosario.html#caliz", icon: "fa-church" },
    { title: "Canonización", desc: "El proceso oficial por el cual el Papa declara que una persona vivió heroicamente la fe y ya está en el Cielo…", cat: "Glosario", url: "glosario.html#canonizacion", icon: "fa-place-of-worship" },
    { title: "Capilla", desc: "Lugar de culto más pequeño que una parroquia, destinado a una comunidad barrial específica. Nuestra Capilla S…", cat: "Glosario", url: "glosario.html#capilla", icon: "fa-map-pin" },
    { title: "Caridad", desc: "La virtud más importante de todas. Es amar a Dios sobre todas las cosas y amar al prójimo con el mismo corazó…", cat: "Glosario", url: "glosario.html#caridad", icon: "fa-praying-hands" },
    { title: "Casulla", desc: "Vestidura exterior (como un poncho) que usa el sacerdote para celebrar la Misa. Su color varía según el tiemp…", cat: "Glosario", url: "glosario.html#casulla", icon: "fa-church" },
    { title: "Catecismo", desc: "El libro oficial que resume de forma clara, ordenada y accesible todo lo que cree, celebra, vive y enseña la…", cat: "Glosario", url: "glosario.html#catecismo", icon: "fa-cross" },
    { title: "Católico", desc: "Palabra de origen griego que significa 'Universal'. La Iglesia es católica porque Jesús la fundó para todo el…", cat: "Glosario", url: "glosario.html#catolico", icon: "fa-cross" },
    { title: "Ceniza (Miércoles de)", desc: "Día que marca el inicio de la Cuaresma. Al recibir la ceniza en la frente recordamos que la vida terrenal es…", cat: "Glosario", url: "glosario.html#ceniza", icon: "fa-church" },
    { title: "Cíngulo", desc: "Cordón que el sacerdote usa para sujetar el alba a la cintura. Simboliza la castidad y recuerda las cuerdas c…", cat: "Glosario", url: "glosario.html#cingulo", icon: "fa-church" },
    { title: "Cisma", desc: "Una ruptura dolorosa dentro de la Iglesia. Ocurre cuando un grupo decide separarse y dejar de reconocer la au…", cat: "Glosario", url: "glosario.html#cisma", icon: "fa-place-of-worship" },
    { title: "Clero", desc: "El conjunto de personas que han recibido el sacramento del Orden Sagrado para servir a la Iglesia: diáconos,…", cat: "Glosario", url: "glosario.html#clero", icon: "fa-place-of-worship" },
    { title: "Comunión", desc: "Recibir el Cuerpo y la Sangre de Cristo en la Misa. También significa la unión profunda de familia que tenemo…", cat: "Glosario", url: "glosario.html#comunion", icon: "fa-church" },
    { title: "Confesión (o Reconciliación)", desc: "El sacramento de la sanación donde le contamos nuestros pecados al sacerdote para recibir el perdón, la paz y…", cat: "Glosario", url: "glosario.html#confesion", icon: "fa-church" },
    { title: "Confirmación", desc: "Sacramento donde renovamos nuestro Bautismo y recibimos la plenitud del Espíritu Santo con sus dones para ser…", cat: "Glosario", url: "glosario.html#confirmacion", icon: "fa-church" },
    { title: "Consagración", desc: "El momento más sagrado de la Misa, donde el sacerdote repite las palabras de la Última Cena y el pan y el vin…", cat: "Glosario", url: "glosario.html#consagracion", icon: "fa-church" },
    { title: "Copón", desc: "Recipiente sagrado, parecido a un cáliz pero más grande y con tapa, donde se guardan las hostias consagradas…", cat: "Glosario", url: "glosario.html#copon", icon: "fa-church" },
    { title: "Corporal", desc: "Paño cuadrado de lino sobre el que se apoyan el cáliz y la patena en el altar para recoger cualquier pequeña…", cat: "Glosario", url: "glosario.html#corporal", icon: "fa-church" },
    { title: "Crisma", desc: "Aceite perfumado y consagrado por el Obispo. Se usa como un 'sello espiritual' imborrable en los sacramentos…", cat: "Glosario", url: "glosario.html#crisma", icon: "fa-church" },
    { title: "Cruz", desc: "El símbolo principal de los cristianos. No es un signo de derrota, sino de victoria y amor extremo: nos recue…", cat: "Glosario", url: "glosario.html#cruz", icon: "fa-cross" },
    { title: "Cuaresma", desc: "Tiempo litúrgico de 40 días antes de la Pascua. Es un tiempo de entrenamiento espiritual, oración y conversió…", cat: "Glosario", url: "glosario.html#cuaresma", icon: "fa-church" },
    { title: "Custodia (u Ostensorio)", desc: "El objeto sagrado, generalmente dorado y con forma de sol, donde se coloca a la vista la Hostia Consagrada pa…", cat: "Glosario", url: "glosario.html#custodia", icon: "fa-church" },
    { title: "Dalmática", desc: "Vestidura exterior propia del diácono, con mangas amplias, que se usa en las celebraciones solemnes por encim…", cat: "Glosario", url: "glosario.html#dalmatica", icon: "fa-church" },
    { title: "Decálogo", desc: "Son los Diez Mandamientos que Dios le dio a Moisés. No son prohibiciones para arruinarnos la vida, sino las '…", cat: "Glosario", url: "glosario.html#decalogo", icon: "fa-book-bible" },
    { title: "Diácono", desc: "Ministro ordenado para servir a la comunidad. Puede bautizar, predicar y presidir casamientos, pero no tiene…", cat: "Glosario", url: "glosario.html#diacono", icon: "fa-place-of-worship" },
    { title: "Dios", desc: "El Creador de todo lo que existe y Padre infinitamente amoroso. En nuestra fe católica, creemos en un solo Di…", cat: "Glosario", url: "glosario.html#dios", icon: "fa-cross" },
    { title: "Diócesis", desc: "Es la 'familia grande' de parroquias y capillas de una región (como la Diócesis a la que pertenece nuestra Ca…", cat: "Glosario", url: "glosario.html#diocesis", icon: "fa-place-of-worship" },
    { title: "Dirección Espiritual", desc: "Es el acompañamiento personal con un sacerdote o guía espiritual capacitado para ayudarnos a escuchar la voz…", cat: "Glosario", url: "glosario.html#direccion-espiritual", icon: "fa-praying-hands" },
    { title: "Dogma", desc: "Una verdad central de la fe que la Iglesia declara como definitiva e incuestionable porque ha sido revelada d…", cat: "Glosario", url: "glosario.html#dogma", icon: "fa-cross" },
    { title: "Dones del Espíritu Santo", desc: "Siete regalos especiales que nos da Dios (Sabiduría, Entendimiento, Consejo, Fortaleza, Ciencia, Piedad y Tem…", cat: "Glosario", url: "glosario.html#dones-espiritu", icon: "fa-cross" },
    { title: "Doxología", desc: "Fórmula de alabanza litúrgica para dar gloria a la Santísima Trinidad. La más importante ocurre en la Misa cu…", cat: "Glosario", url: "glosario.html#doxologia", icon: "fa-church" },
    { title: "Ecumenismo", desc: "Es el esfuerzo, la oración y el diálogo que busca recuperar la unidad entre todos los cristianos del mundo (c…", cat: "Glosario", url: "glosario.html#ecumenismo", icon: "fa-place-of-worship" },
    { title: "Encarnación", desc: "El misterio inmenso por el cual el Hijo de Dios se hizo hombre en el vientre de la Virgen María para vivir en…", cat: "Glosario", url: "glosario.html#encarnacion", icon: "fa-cross" },
    { title: "Encíclica", desc: "Una carta solemne que el Papa envía a toda la Iglesia para enseñar, aclarar o reflexionar sobre temas importa…", cat: "Glosario", url: "glosario.html#enciclica", icon: "fa-place-of-worship" },
    { title: "Epifanía", desc: "Significa 'manifestación'. Es la fiesta donde recordamos que Jesús se mostró al mundo entero, representado en…", cat: "Glosario", url: "glosario.html#epifania", icon: "fa-church" },
    { title: "Epístola", desc: "Nombre que reciben las cartas escritas por los apóstoles (como San Pablo o San Pedro) que se encuentran en el…", cat: "Glosario", url: "glosario.html#epistola", icon: "fa-book-bible" },
    { title: "Escapulario", desc: "Un signo de devoción, generalmente de tela, que se lleva sobre el pecho y la espalda como símbolo de protecci…", cat: "Glosario", url: "glosario.html#escapulario", icon: "fa-praying-hands" },
    { title: "Esperanza", desc: "Una de las tres virtudes teologales. Es la confianza firme de que Dios cumplirá sus promesas y nos dará la fu…", cat: "Glosario", url: "glosario.html#esperanza", icon: "fa-praying-hands" },
    { title: "Espíritu Santo", desc: "La Tercera Persona de la Santísima Trinidad. Es el amor vivo entre el Padre y el Hijo que nos guía, nos da fu…", cat: "Glosario", url: "glosario.html#espiritu-santo", icon: "fa-cross" },
    { title: "Estola", desc: "Banda larga de tela que el sacerdote lleva al cuello y el diácono cruzada. Es el símbolo de la autoridad espi…", cat: "Glosario", url: "glosario.html#estola", icon: "fa-church" },
    { title: "Eucaristía", desc: "Significa 'acción de gracias'. Es el sacramento central de nuestra fe, donde recibimos verdaderamente el Cuer…", cat: "Glosario", url: "glosario.html#eucaristia", icon: "fa-church" },
    { title: "Evangelio", desc: "Significa 'Buena Noticia'. Son los cuatro libros principales de la Biblia (Mateo, Marcos, Lucas y Juan) que n…", cat: "Glosario", url: "glosario.html#evangelio", icon: "fa-book-bible" },
    { title: "Evangelización", desc: "La misión principal de todo cristiano: compartir con otros, mediante palabras y con el propio ejemplo de vida…", cat: "Glosario", url: "glosario.html#evangelizacion", icon: "fa-praying-hands" },
    { title: "Examen de Conciencia", desc: "Práctica de detenerse a revisar nuestras acciones y pensamientos frente a Dios para agradecer lo bueno y pedi…", cat: "Glosario", url: "glosario.html#examen-conciencia", icon: "fa-praying-hands" },
    { title: "Excomunión", desc: "Pena grave por la cual una persona queda apartada de la comunión de la Iglesia debido a una falta muy seria,…", cat: "Glosario", url: "glosario.html#excomunion", icon: "fa-place-of-worship" },
    { title: "Exequias", desc: "Ritos y oraciones que la Iglesia celebra para despedir a un difunto, encomendando su alma a la misericordia d…", cat: "Glosario", url: "glosario.html#exequias", icon: "fa-church" },
    { title: "Fe", desc: "Es un regalo de Dios y nuestra respuesta de confianza total en Él, aceptando como verdad lo que Él nos ha rev…", cat: "Glosario", url: "glosario.html#fe", icon: "fa-cross" },
    { title: "Feligrés", desc: "Persona bautizada que pertenece, asiste y participa activamente en la vida de una comunidad parroquial o capi…", cat: "Glosario", url: "glosario.html#feligres", icon: "fa-map-pin" },
    { title: "Genuflexión", desc: "Gesto de doblar la rodilla derecha hasta tocar el suelo como señal de máxima adoración y respeto, reservado ú…", cat: "Glosario", url: "glosario.html#genuflexion", icon: "fa-church" },
    { title: "Gloria", desc: "Oración muy antigua de alabanza a la Santísima Trinidad que se canta en la Misa. También se refiere al estado…", cat: "Glosario", url: "glosario.html#gloria", icon: "fa-church" },
    { title: "Gracia", desc: "Es la vida de Dios actuando en nosotros. Un regalo totalmente gratuito que nos santifica, nos ayuda a vencer…", cat: "Glosario", url: "glosario.html#gracia", icon: "fa-cross" },
    { title: "Herejía", desc: "Es negar o dudar con terquedad y de forma consciente de una verdad de fe que ha sido declarada oficialmente p…", cat: "Glosario", url: "glosario.html#herejia", icon: "fa-cross" },
    { title: "Hisopo", desc: "Objeto litúrgico (generalmente una varilla metálica con una esfera perforada) que el sacerdote usa para rocia…", cat: "Glosario", url: "glosario.html#hisopo", icon: "fa-church" },
    { title: "Homilía", desc: "Explicación de la Palabra de Dios que hace el sacerdote o el diácono durante la Misa para ayudarnos a entende…", cat: "Glosario", url: "glosario.html#homilia", icon: "fa-church" },
    { title: "Hostia", desc: "Pan de trigo sin levadura que, tras el momento de la consagración en la Misa, deja de ser pan para convertirs…", cat: "Glosario", url: "glosario.html#hostia", icon: "fa-church" },
    { title: "Iglesia", desc: "La inmensa familia de todos los bautizados que siguen a Jesús en el mundo. También se refiere al templo o edi…", cat: "Glosario", url: "glosario.html#iglesia", icon: "fa-place-of-worship" },
    { title: "Incienso", desc: "Resina aromática que al quemarse produce un humo perfumado. En la liturgia, simboliza nuestra oración que sub…", cat: "Glosario", url: "glosario.html#incienso", icon: "fa-church" },
    { title: "Incensario (o Turíbulo)", desc: "Recipiente de metal que cuelga de cadenas donde se quema el incienso con carbones encendidos para honrar a Di…", cat: "Glosario", url: "glosario.html#incensario", icon: "fa-church" },
    { title: "Indulgencia", desc: "Ayuda espiritual especial que la Iglesia ofrece para sanar las secuelas o 'huellas' que dejan en nuestra alma…", cat: "Glosario", url: "glosario.html#indulgencia", icon: "fa-cross" },
    { title: "Infalibilidad", desc: "Don del Espíritu Santo que garantiza que el Papa no se equivoque únicamente cuando enseña de forma solemne y…", cat: "Glosario", url: "glosario.html#infalibilidad", icon: "fa-cross" },
    { title: "Infierno", desc: "Estado de separación eterna y dolorosa de Dios, elegido libremente por quien rechaza su amor, su misericordia…", cat: "Glosario", url: "glosario.html#infierno", icon: "fa-cross" },
    { title: "Inmaculada Concepción", desc: "Dogma que enseña que la Virgen María fue preservada de todo pecado (incluso el original) desde el primer inst…", cat: "Glosario", url: "glosario.html#inmaculada", icon: "fa-cross" },
    { title: "Intercesión", desc: "Acción de pedir a Dios en favor de otros. Los santos y la Virgen María interceden constantemente por nosotros…", cat: "Glosario", url: "glosario.html#intercesion", icon: "fa-praying-hands" },
    { title: "Jesús (o Jesucristo)", desc: "El Hijo de Dios hecho hombre, la Segunda Persona de la Trinidad. Es nuestro Salvador y el centro absoluto de…", cat: "Glosario", url: "glosario.html#jesus", icon: "fa-cross" },
    { title: "Jueves Santo", desc: "Día de la Semana Santa en que celebramos la Última Cena. Allí Jesús nos dejó la Eucaristía, instituyó el Sace…", cat: "Glosario", url: "glosario.html#jueves-santo", icon: "fa-church" },
    { title: "Juicio Final", desc: "Momento al final de los tiempos donde Jesús volverá con gloria para revelar la verdad de cada corazón, juzgar…", cat: "Glosario", url: "glosario.html#juicio-final", icon: "fa-cross" },
    { title: "Kerigma", desc: "Es el anuncio básico, alegre y fundamental de nuestra fe: Jesús te ama inmensamente, dio su vida para salvart…", cat: "Glosario", url: "glosario.html#kerigma", icon: "fa-cross" },
    { title: "Laico", desc: "Todo cristiano bautizado que, sin ser sacerdote ni religioso, tiene la enorme misión de transformar el mundo…", cat: "Glosario", url: "glosario.html#laico", icon: "fa-place-of-worship" },
    { title: "Leccionario", desc: "Libro litúrgico grande que se coloca en el ambón y que contiene las lecturas de la Biblia que se proclaman du…", cat: "Glosario", url: "glosario.html#leccionario", icon: "fa-church" },
    { title: "Lectio Divina", desc: "Método antiguo y profundo de oración que consiste en leer la Biblia con fe, meditando qué nos dice Dios perso…", cat: "Glosario", url: "glosario.html#lectio-divina", icon: "fa-praying-hands" },
    { title: "Limosna", desc: "Gesto concreto de caridad que consiste en compartir nuestros bienes materiales con los necesitados, como sign…", cat: "Glosario", url: "glosario.html#limosna", icon: "fa-praying-hands" },
    { title: "Liturgia", desc: "Celebración oficial, pública y comunitaria de la Iglesia donde Jesús mismo actúa para santificarnos, especial…", cat: "Glosario", url: "glosario.html#liturgia", icon: "fa-church" },
    { title: "Magisterio", desc: "La autoridad de enseñanza de la Iglesia (formada por el Papa y los obispos unidos a él), encargada de cuidar,…", cat: "Glosario", url: "glosario.html#magisterio", icon: "fa-place-of-worship" },
    { title: "Mandamientos (Los Diez)", desc: "La Ley de Dios dada a Moisés y perfeccionada por Jesús. Se resumen en dos: Amar a Dios sobre todas las cosas…", cat: "Glosario", url: "glosario.html#mandamientos", icon: "fa-cross" },
    { title: "Mártir", desc: "Palabra que significa 'testigo'. Es una persona que ama tanto a Dios que está dispuesta a sufrir o entregar s…", cat: "Glosario", url: "glosario.html#martir", icon: "fa-cross" },
    { title: "Matrimonio", desc: "Sacramento por el cual un hombre y una mujer se unen en una alianza de amor para toda la vida, con la bendici…", cat: "Glosario", url: "glosario.html#matrimonio", icon: "fa-church" },
    { title: "Misa", desc: "La celebración más importante de la Iglesia. Es el memorial donde se hace presente el sacrificio de Jesús en…", cat: "Glosario", url: "glosario.html#misa", icon: "fa-church" },
    { title: "Misericordia", desc: "El amor incondicional de Dios que se inclina hacia nuestra miseria y debilidad para perdonarnos, sanarnos y d…", cat: "Glosario", url: "glosario.html#misericordia", icon: "fa-cross" },
    { title: "Misión", desc: "El llamado de todo cristiano a salir de su comodidad para llevar el amor de Dios a los demás, especialmente a…", cat: "Glosario", url: "glosario.html#mision", icon: "fa-praying-hands" },
    { title: "Misterio", desc: "Una verdad tan inmensa sobre Dios que nuestra mente humana no puede comprender por completo, pero que aceptam…", cat: "Glosario", url: "glosario.html#misterio", icon: "fa-cross" },
    { title: "Mitra", desc: "Gorro alto y terminado en punta que usan los Obispos durante las celebraciones como signo de su autoridad esp…", cat: "Glosario", url: "glosario.html#mitra", icon: "fa-church" },
    { title: "Monaguillo", desc: "Niño, joven o laico que asiste muy de cerca al sacerdote en el altar durante la Misa y otras celebraciones li…", cat: "Glosario", url: "glosario.html#monaguillo", icon: "fa-church" },
    { title: "Navidad", desc: "La hermosa fiesta del nacimiento de Jesús en Belén. Celebramos que Dios se hace hombre, pequeño y humilde, pa…", cat: "Glosario", url: "glosario.html#navidad", icon: "fa-church" },
    { title: "Naveta", desc: "Recipiente pequeño, generalmente con forma de barquito, donde se guarda el incienso antes de ponerlo sobre lo…", cat: "Glosario", url: "glosario.html#naveta", icon: "fa-church" },
    { title: "Novena", desc: "Devoción de rezar durante nueve días seguidos por una intención especial, imitando la espera perseverante de…", cat: "Glosario", url: "glosario.html#novena", icon: "fa-praying-hands" },
    { title: "Obispo", desc: "Sucesor directo de los apóstoles encargado de guiar, enseñar y santificar a toda una Diócesis. Los sacerdotes…", cat: "Glosario", url: "glosario.html#obispo", icon: "fa-place-of-worship" },
    { title: "Oración", desc: "Hablar con Dios como con un amigo íntimo. Es elevar el corazón para escucharlo, darle gracias, pedirle perdón…", cat: "Glosario", url: "glosario.html#oracion", icon: "fa-praying-hands" },
    { title: "Orden Sagrado", desc: "El sacramento por el cual algunos hombres son consagrados con un don especial del Espíritu Santo para servir…", cat: "Glosario", url: "glosario.html#orden-sagrado", icon: "fa-church" },
    { title: "Ornamentos Litúrgicos", desc: "Conjunto de vestiduras (alba, estola, casulla) y telas sagradas que usa el sacerdote para celebrar la Misa co…", cat: "Glosario", url: "glosario.html#ornamentos", icon: "fa-church" },
    { title: "Padre Nuestro", desc: "La oración por excelencia de los cristianos. Fue enseñada directamente por Jesús a sus apóstoles y resume tod…", cat: "Glosario", url: "glosario.html#padre-nuestro", icon: "fa-praying-hands" },
    { title: "Padrinos", desc: "Personas elegidas en el Bautismo y la Confirmación para acompañar, guiar y ser un buen ejemplo de fe y vida c…", cat: "Glosario", url: "glosario.html#padrinos", icon: "fa-church" },
    { title: "Palia", desc: "Lienzo cuadrado y rígido que se pone sobre el cáliz durante la Misa para proteger la Sangre de Cristo de cual…", cat: "Glosario", url: "glosario.html#palia", icon: "fa-church" },
    { title: "Papa", desc: "El Obispo de Roma y sucesor de San Pedro. Es el pastor visible de toda la Iglesia Católica en el mundo y el g…", cat: "Glosario", url: "glosario.html#papa", icon: "fa-place-of-worship" },
    { title: "Párroco", desc: "Sacerdote designado por el Obispo para ser el pastor, guía y responsable principal de una Parroquia y de toda…", cat: "Glosario", url: "glosario.html#parroco", icon: "fa-place-of-worship" },
    { title: "Parroquia", desc: "Comunidad central de fieles guiada por un párroco. Una capilla es como el 'brazo barrial' que pertenece y tra…", cat: "Glosario", url: "glosario.html#parroquia", icon: "fa-map-pin" },
    { title: "Pascua", desc: "La fiesta más grande de nuestra fe. Celebramos con inmensa alegría que Jesús venció a la muerte y resucitó, a…", cat: "Glosario", url: "glosario.html#pascua", icon: "fa-church" },
    { title: "Pastoral", desc: "Todas las acciones, grupos y trabajos organizados que hace la Iglesia (como la catequesis o la ayuda solidari…", cat: "Glosario", url: "glosario.html#pastoral", icon: "fa-place-of-worship" },
    { title: "Patena", desc: "Plato redondo de metal precioso donde se coloca la Hostia grande que el sacerdote consagra en el altar durant…", cat: "Glosario", url: "glosario.html#patena", icon: "fa-church" },
    { title: "Patrona", desc: "Santa elegida como protectora y modelo de una comunidad. Nuestra patrona intercede por nuestro barrio; como a…", cat: "Glosario", url: "glosario.html#patrona", icon: "fa-map-pin" },
    { title: "Pecado", desc: "Rechazar voluntariamente el amor de Dios. No es solo romper una regla, es una herida profunda en nuestra rela…", cat: "Glosario", url: "glosario.html#pecado", icon: "fa-praying-hands" },
    { title: "Pentecostés", desc: "Gran fiesta que celebra la venida del Espíritu Santo sobre la Virgen María y los apóstoles. Es el nacimiento…", cat: "Glosario", url: "glosario.html#pentecostes", icon: "fa-church" },
    { title: "Procesión", desc: "Caminar juntos por las calles rezando y cantando detrás de una imagen sagrada. Simboliza que somos un pueblo…", cat: "Glosario", url: "glosario.html#procesion", icon: "fa-map-pin" },
    { title: "Providencia (Divina)", desc: "El cuidado amoroso, constante y detallista con el que Dios guía, protege y sostiene toda la creación y la vid…", cat: "Glosario", url: "glosario.html#providencia", icon: "fa-cross" },
    { title: "Purgatorio", desc: "Estado de purificación después de la muerte. Es como un 'hospital del alma' para quienes mueren amando a Dios…", cat: "Glosario", url: "glosario.html#purgatorio", icon: "fa-cross" },
    { title: "Purificador", desc: "Pequeño lienzo de lino blanco que el sacerdote usa para limpiar el cáliz, la patena y sus dedos después de da…", cat: "Glosario", url: "glosario.html#purificador", icon: "fa-church" },
    { title: "Querubín", desc: "Ángel perteneciente a un coro celestial muy cercano a Dios. Su nombre significa 'los que rezan' o 'los que in…", cat: "Glosario", url: "glosario.html#querubin", icon: "fa-cross" },
    { title: "Redención", desc: "La obra inmensa de amor por la cual Jesús, con su muerte y resurrección, nos liberó de la esclavitud del peca…", cat: "Glosario", url: "glosario.html#redencion", icon: "fa-cross" },
    { title: "Reliquia", desc: "Restos mortales u objetos asociados a un santo, que veneramos con respeto porque nos recuerdan su ejemplo de…", cat: "Glosario", url: "glosario.html#reliquia", icon: "fa-praying-hands" },
    { title: "Resurrección", desc: "El misterio central de nuestra fe. Jesús, después de morir en la cruz, volvió a la vida al tercer día, vencie…", cat: "Glosario", url: "glosario.html#resurreccion", icon: "fa-cross" },
    { title: "Retablo", desc: "Estructura de madera, piedra o mármol que se coloca detrás del altar, decorada con imágenes de santos o escen…", cat: "Glosario", url: "glosario.html#retablo", icon: "fa-church" },
    { title: "Rosario", desc: "Oración contemplativa bellísima donde recorremos la vida de Jesús de la mano de María, repitiendo el Avemaría…", cat: "Glosario", url: "glosario.html#rosario", icon: "fa-praying-hands" },
    { title: "Sacerdote", desc: "Hombre consagrado que actúa en nombre de Cristo para celebrar la Misa, perdonar los pecados y guiar a la comu…", cat: "Glosario", url: "glosario.html#sacerdote", icon: "fa-place-of-worship" },
    { title: "Sacramento", desc: "Signo visible instituido por Jesús para darnos su Gracia invisible. Son los siete canales directos por los qu…", cat: "Glosario", url: "glosario.html#sacramento", icon: "fa-church" },
    { title: "Sagrario", desc: "El lugar más sagrado de nuestra Capilla. Es el cofre o mueble seguro donde se guarda la Eucaristía para que p…", cat: "Glosario", url: "glosario.html#sagrario", icon: "fa-map-pin" },
    { title: "Salvación", desc: "El regalo inmenso de Dios que nos rescata del mal y del pecado, ofreciéndonos la oportunidad de vivir felices…", cat: "Glosario", url: "glosario.html#salvacion", icon: "fa-cross" },
    { title: "Santa Ana", desc: "Nuestra patrona. Es la madre de la Virgen María y abuela de Jesús. Como buena abuela, nos cuida, nos escucha…", cat: "Glosario", url: "glosario.html#santa-ana", icon: "fa-map-pin" },
    { title: "Santísima Trinidad", desc: "El misterio de un solo Dios en tres Personas distintas: Padre, Hijo y Espíritu Santo. Una comunidad eterna de…", cat: "Glosario", url: "glosario.html#santisima-trinidad", icon: "fa-cross" },
    { title: "Santo / Santa", desc: "Persona que ya goza de la presencia de Dios en el Cielo. Son modelos de vida cristiana y amigos incondicional…", cat: "Glosario", url: "glosario.html#santo", icon: "fa-cross" },
    { title: "Sínodo", desc: "Asamblea de obispos y otros fieles que se reúnen para ayudar al Papa en el gobierno de la Iglesia, buscando s…", cat: "Glosario", url: "glosario.html#sinodo", icon: "fa-place-of-worship" },
    { title: "Solideo", desc: "Pequeño gorro circular que usan los obispos y el Papa. Su nombre significa 'solo a Dios' y se lo quitan ante…", cat: "Glosario", url: "glosario.html#solideo", icon: "fa-church" },
    { title: "Tabernáculo", desc: "Otro nombre para referirse al Sagrario. Nos recuerda la 'tienda de campaña' donde los antiguos israelitas gua…", cat: "Glosario", url: "glosario.html#tabernaculo", icon: "fa-map-pin" },
    { title: "Tradición", desc: "La Palabra de Dios que fue transmitida de forma oral por los apóstoles con sus enseñanzas y que la Iglesia co…", cat: "Glosario", url: "glosario.html#tradicion", icon: "fa-cross" },
    { title: "Transustanciación", desc: "El gran milagro que ocurre en la Misa cuando el pan y el vino se convierten real y sustancialmente en el Cuer…", cat: "Glosario", url: "glosario.html#transustanciacion", icon: "fa-church" },
    { title: "Unción de los Enfermos", desc: "Sacramento que da fuerza, paz y el perdón de los pecados a quienes sufren por una enfermedad grave, una cirug…", cat: "Glosario", url: "glosario.html#uncion-enfermos", icon: "fa-church" },
    { title: "Vaticano", desc: "La sede central de la Iglesia Católica en Roma. Es un Estado independiente donde vive el Papa y se encuentra…", cat: "Glosario", url: "glosario.html#vaticano", icon: "fa-place-of-worship" },
    { title: "Veneración", desc: "Acto de respeto, honra y cariño que le damos a la Virgen María y a los Santos por ser grandes amigos de Dios…", cat: "Glosario", url: "glosario.html#veneracion", icon: "fa-cross" },
    { title: "Vía Crucis", desc: "Camino de oración que recorre las catorce estaciones de los últimos momentos de Jesús, desde que fue condenad…", cat: "Glosario", url: "glosario.html#via-crucis", icon: "fa-praying-hands" },
    { title: "Vida Eterna", desc: "La promesa hermosa de Jesús de que la muerte no es el final, sino el paso definitivo a una vida de felicidad…", cat: "Glosario", url: "glosario.html#vida-eterna", icon: "fa-cross" },
    { title: "Vigilia", desc: "Estar en vela esperando al Señor. Es la oración atenta que se hace la noche anterior a una gran fiesta cristi…", cat: "Glosario", url: "glosario.html#vigilia", icon: "fa-church" },
    { title: "Virgen María", desc: "La madre de Jesús y madre nuestra. Es la criatura más perfecta amada por Dios, ejemplo máximo de fe, humildad…", cat: "Glosario", url: "glosario.html#virgen-maria", icon: "fa-cross" },
    { title: "Virtud", desc: "Un hábito firme que nos inclina a hacer siempre el bien de manera fácil y alegre. Se fortalecen con la prácti…", cat: "Glosario", url: "glosario.html#virtud", icon: "fa-praying-hands" },
    { title: "Vocación", desc: "El llamado único y especial que Dios le hace a cada persona para ser feliz y servir a los demás (puede ser al…", cat: "Glosario", url: "glosario.html#vocacion", icon: "fa-praying-hands" },
    { title: "XP (Crismón)", desc: "Monograma sagrado formado por las letras griegas X (Ji) y P (Ro), que son las iniciales del nombre de Cristo.…", cat: "Glosario", url: "glosario.html#xp-crismon", icon: "fa-church" },
    { title: "Yahvé", desc: "Nombre sagrado de Dios revelado a Moisés. Significa 'Yo soy el que soy', indicando que Él es la fuente inagot…", cat: "Glosario", url: "glosario.html#yahve", icon: "fa-book-bible" },
    { title: "Zaqueo", desc: "Personaje bíblico de baja estatura que, por curiosidad, se subió a un árbol para ver pasar a Jesús. Represent…", cat: "Glosario", url: "glosario.html#zaqueo", icon: "fa-book-bible" },

    // 75 intercesores del Botiquín Espiritual / Santoral
    { title: "San José de Cupertino", desc: "Patrono de: Estudiantes y Exámenes Difíciles", cat: "Santoral", url: "santoral.html?santo=san-jose-cupertino", icon: "fa-book-open-reader" },
    { title: "Santo Tomás de Aquino", desc: "Patrono de: Estudiantes, Sabiduría y Verdad", cat: "Santoral", url: "santoral.html?santo=santo-tomas-aquino", icon: "fa-lightbulb" },
    { title: "Santa Teresa de Ávila", desc: "Patrono de: Psicólogos y Buscadores de paz interior", cat: "Santoral", url: "santoral.html?santo=santa-teresa-avila", icon: "fa-castle" },
    { title: "Santa Dinfna", desc: "Patrono de: Salud Mental y Ansiedad", cat: "Santoral", url: "santoral.html?santo=santa-dinfna", icon: "fa-brain" },
    { title: "San Gabriel Brochero", desc: "Patrono de: Paisanos y Gente de campo", cat: "Santoral", url: "santoral.html?santo=cura-brochero", icon: "fa-mule" },
    { title: "San Isidro Labrador", desc: "Patrono de: Agricultores y Huertas", cat: "Santoral", url: "santoral.html?santo=san-isidro-labrador", icon: "fa-seedling" },
    { title: "Santiago Apóstol", desc: "Patrono de: Jinetes y Cabalgatas", cat: "Santoral", url: "santoral.html?santo=santiago-apostol", icon: "fa-horse" },
    { title: "Virgen de la Dulce Espera", desc: "Patrono de: Embarazadas y Deseo de hijos", cat: "Santoral", url: "santoral.html?santo=virgen-dulce-espera", icon: "fa-person-pregnant" },
    { title: "San Gerardo Mayela", desc: "Patrono de: Madres Gestantes y Niños", cat: "Santoral", url: "santoral.html?santo=san-gerardo-mayela", icon: "fa-hands-holding-child" },
    { title: "San Simeón", desc: "Patrono de: Ancianos y Sabiduría", cat: "Santoral", url: "santoral.html?santo=san-simeon", icon: "fa-person-cane" },
    { title: "San Nicolás de Bari", desc: "Patrono de: Niños y Desamparados", cat: "Santoral", url: "santoral.html?santo=san-nicolas-de-bari", icon: "fa-child-reaching" },
    { title: "San Expedito", desc: "Patrono de: Causas Urgentes", cat: "Santoral", url: "santoral.html?santo=san-expedito", icon: "fa-stopwatch" },
    { title: "San Judas Tadeo", desc: "Patrono de: Causas Imposibles", cat: "Santoral", url: "santoral.html?santo=san-judas-tadeo", icon: "fa-hands-praying" },
    { title: "Beato Ceferino Namuncurá", desc: "Patrono de: Jóvenes, Aspiraciones y la Patagonia", cat: "Santoral", url: "santoral.html?santo=san-ceferino", icon: "fa-mountain-sun" },
    { title: "Virgen de la Merced", desc: "Patrono de: Libertad, Cautivos y Fuerzas Armadas", cat: "Santoral", url: "santoral.html?santo=virgen-merced", icon: "fa-key" },
    { title: "Virgen de Itatí", desc: "Patrono de: Patrona del Litoral", cat: "Santoral", url: "santoral.html?santo=virgen-itati", icon: "fa-water" },
    { title: "Santa Cecilia", desc: "Patrono de: Músicos, Cantantes y Poetas", cat: "Santoral", url: "santoral.html?santo=santa-cecilia", icon: "fa-music" },
    { title: "San Alberto Magno", desc: "Patrono de: Científicos y Estudiantes de Ciencias Naturales", cat: "Santoral", url: "santoral.html?santo=san-alberto-magno", icon: "fa-microscope" },
    { title: "San Ignacio de Loyola", desc: "Patrono de: Ejercicios Espirituales y Discernimiento", cat: "Santoral", url: "santoral.html?santo=san-ignacio-loyola", icon: "fa-compass" },
    { title: "Santa Águeda", desc: "Patrono de: Enfermedades del Pecho y las Mamas", cat: "Santoral", url: "santoral.html?santo=santa-agueda", icon: "fa-ribbon" },
    { title: "Santa Apolonia", desc: "Patrono de: Dentistas y Dolores de Muelas", cat: "Santoral", url: "santoral.html?santo=santa-apolonia", icon: "fa-tooth" },
    { title: "San Sebastián", desc: "Patrono de: Deportistas y contra Epidemias", cat: "Santoral", url: "santoral.html?santo=san-sebastian", icon: "fa-person-running" },
    { title: "San Francisco Javier", desc: "Patrono de: Misioneros y Viajes Largos", cat: "Santoral", url: "santoral.html?santo=san-francisco-javier", icon: "fa-earth-americas" },
    { title: "San Benito de Nursia", desc: "Patrono de: Fundador de los Monjes y Europa", cat: "Santoral", url: "santoral.html?santo=san-benito-abad", icon: "fa-scroll" },
    { title: "Santa Clara de Asís", desc: "Patrono de: Televisión, Telecomunicaciones y Claridad", cat: "Santoral", url: "santoral.html?santo=santa-clara-asis", icon: "fa-sun" },
    { title: "Santo Domingo de Guzmán", desc: "Patrono de: Predicadores y el Santo Rosario", cat: "Santoral", url: "santoral.html?santo=santo-domingo-guzman", icon: "fa-ellipsis-vertical" },
    { title: "San Bernardo de Claraval", desc: "Patrono de: Buscadores de Dios y Escritores", cat: "Santoral", url: "santoral.html?santo=san-bernardo-claraval", icon: "fa-feather" },
    { title: "San Camilo de Lellis", desc: "Patrono de: Enfermeros y Hospitales", cat: "Santoral", url: "santoral.html?santo=san-camilo-lellis", icon: "fa-hand-holding-cross" },
    { title: "San Alfonso María de Ligorio", desc: "Patrono de: Confesores y Teólogos Morales", cat: "Santoral", url: "santoral.html?santo=san-alfonso-ligorio", icon: "fa-book-bible" },
    { title: "Santa Faustina Kowalska", desc: "Patrono de: Apóstol de la Divina Misericordia", cat: "Santoral", url: "santoral.html?santo=santa-faustina", icon: "fa-sun" },
    { title: "Virgen de la Sonrisa", desc: "Patrono de: Depresión, Tristeza y Ansiedad", cat: "Santoral", url: "santoral.html?santo=virgen-de-la-sonrisa", icon: "fa-face-smile-beam" },
    { title: "San Francisco de Sales", desc: "Patrono de: Escritores, Periodistas y la Mansedumbre", cat: "Santoral", url: "santoral.html?santo=san-francisco-de-sales", icon: "fa-feather-pointed" },
    { title: "Santa Rosa de Lima", desc: "Patrono de: Patrona de América, Perú y las Flores", cat: "Santoral", url: "santoral.html?santo=santa-rosa-de-lima", icon: "fa-clover" },
    { title: "San Roque de Santa Cruz", desc: "Patrono de: Mártir de las Misiones del Río de la Plata", cat: "Santoral", url: "santoral.html?santo=san-roque-gonzalez", icon: "fa-heart-circle-check" },
    { title: "Santa Isabel de Hungría", desc: "Patrono de: Cáritas, Enfermeros y los necesitados", cat: "Santoral", url: "santoral.html?santo=santa-isabel-hungria", icon: "fa-basket-shopping" },
    { title: "San Agustín de Hipona", desc: "Patrono de: Buscadores de la Verdad y la Conversión", cat: "Santoral", url: "santoral.html?santo=san-agustin", icon: "fa-book" },
    { title: "San Jerónimo", desc: "Patrono de: Bibliotecarios, Traductores y Estudiosos", cat: "Santoral", url: "santoral.html?santo=san-jeronimo", icon: "fa-book-atlas" },
    { title: "Santa Marta de Betania", desc: "Patrono de: Amas de casa, Cocineros y Paz en el hogar", cat: "Santoral", url: "santoral.html?santo=santa-marta", icon: "fa-utensils" },
    { title: "San Florián", desc: "Patrono de: Bomberos y contra Incendios", cat: "Santoral", url: "santoral.html?santo=san-florian", icon: "fa-fire-extinguisher" },
    { title: "San Rafael Arcángel", desc: "Patrono de: Medicina de Dios y Guía de Viajeros", cat: "Santoral", url: "santoral.html?santo=san-rafael-arcangel", icon: "fa-staff-snake" },
    { title: "San Ivo de Kermartin", desc: "Patrono de: Abogados, Jueces y Causas de Justicia", cat: "Santoral", url: "santoral.html?santo=san-ivo", icon: "fa-scale-balanced" },
    { title: "San Bernardino de Siena", desc: "Patrono de: Negocios, Comerciantes y Trabajo Honesto", cat: "Santoral", url: "santoral.html?santo=san-bernardino", icon: "fa-briefcase" },
    { title: "San Juan Crisóstomo", desc: "Patrono de: Predicadores y Defensores de la Verdad", cat: "Santoral", url: "santoral.html?santo=san-juan-crisostomo", icon: "fa-comment-dots" },
    { title: "San Justino Mártir", desc: "Patrono de: Filósofos y Pensadores", cat: "Santoral", url: "santoral.html?santo=san-justino", icon: "fa-head-side-think" },
    { title: "Santa Teresa Benedicta (Edith Stein)", desc: "Patrono de: Filósofos y Personas en búsqueda de sentido", cat: "Santoral", url: "santoral.html?santo=santa-teresa-benedicta", icon: "fa-glasses" },
    { title: "San Francisco de Asís", desc: "Patrono de: Ecología, Animales y Medio Ambiente", cat: "Santoral", url: "santoral.html?santo=san-francisco-asis", icon: "fa-leaf" },
    { title: "San Fiacre", desc: "Patrono de: Jardineros, Huertas y Hierbas Medicinales", cat: "Santoral", url: "santoral.html?santo=san-fiacre", icon: "fa-seedling" },
    { title: "San Huberto", desc: "Patrono de: Ecología y Cuidado de los Bosques", cat: "Santoral", url: "santoral.html?santo=san-huberto", icon: "fa-tree" },
    { title: "Virgen del Rosario de San Nicolás", desc: "Patrono de: Unión de la Familia y Oración", cat: "Santoral", url: "santoral.html?santo=virgen-san-nicolas", icon: "fa-hands-praying" },
    { title: "San Pantaleón", desc: "Patrono de: Médicos y Enfermos", cat: "Santoral", url: "santoral.html?santo=san-pantaleon", icon: "fa-stethoscope" },
    { title: "Santa Gema Galgani", desc: "Patrono de: Farmacéuticos y Problemas de Espalda", cat: "Santoral", url: "santoral.html?santo=san-gema", icon: "fa-bone" },
    { title: "Santa Teresita del Niño Jesús", desc: "Patrono de: Misiones, Confianza y Pequeños Milagros", cat: "Santoral", url: "santoral.html?santo=santa-teresita-lisieux", icon: "fa-spa" },
    { title: "San Cosme y San Damián", desc: "Patrono de: Cirujanos, Médicos y Farmacéuticos", cat: "Santoral", url: "santoral.html?santo=san-cosme-damian", icon: "fa-kit-medical" },
    { title: "Santa Rita de Casia", desc: "Patrono de: Matrimonios Difíciles y Causas Desesperadas", cat: "Santoral", url: "santoral.html?santo=santa-rita", icon: "fa-rings-wedding" },
    { title: "San Martín de Porres", desc: "Patrono de: Justicia Social y Armonía entre las Personas", cat: "Santoral", url: "santoral.html?santo=san-martin-porres", icon: "fa-broom" },
    { title: "Virgen de la Paz", desc: "Patrono de: Concordia, Familia y Fin de Conflictos", cat: "Santoral", url: "santoral.html?santo=virgen-de-la-paz", icon: "fa-dove" },
    { title: "Nuestra Señora de los Dolores", desc: "Patrono de: Consuelo en el Duelo y el Sufrimiento", cat: "Santoral", url: "santoral.html?santo=virgen-dolores", icon: "fa-heart-crack" },
    { title: "Santa Paula de Roma", desc: "Patrono de: Viudas y Personas en Duelo", cat: "Santoral", url: "santoral.html?santo=santa-paula", icon: "fa-person-dress-burst" },
    { title: "San Nicolás de Tolentino", desc: "Patrono de: Intercesor por las Almas y el Alivio del Duelo", cat: "Santoral", url: "santoral.html?santo=san-nicolas-tolentino", icon: "fa-cloud" },
    { title: "Santa Catalina de Alejandría", desc: "Patrono de: Filósofos, Oradores y la Lógica", cat: "Santoral", url: "santoral.html?santo=santa-catalina-alejandria", icon: "fa-gear" },
    { title: "San Isidoro de Sevilla", desc: "Patrono de: Internet, Informática y Nuevos Medios", cat: "Santoral", url: "santoral.html?santo=san-isidoro", icon: "fa-laptop-code" },
    { title: "Santa Gertrudis de Nivelles", desc: "Patrono de: Viajeros y Personas en el camino", cat: "Santoral", url: "santoral.html?santo=santa-gertrudis-nivelles", icon: "fa-map-location-dot" },
    { title: "Nuestra Señora de la Guía", desc: "Patrono de: Caminos Inciertos y Decisiones de Ruta", cat: "Santoral", url: "santoral.html?santo=virgen-de-la-guia", icon: "fa-compass" },
    { title: "San José", desc: "Patrono de: Padres adoptivos, Trabajadores y la Familia", cat: "Santoral", url: "santoral.html?santo=san-jose", icon: "fa-hammer" },
    { title: "San Juan Macías", desc: "Patrono de: Amantes de los animales y los Marginados", cat: "Santoral", url: "santoral.html?santo=san-juan-macias", icon: "fa-paw" },
    { title: "Santa Hildegarda de Bingen", desc: "Patrono de: Medicina Natural, Música y Ecología Femenina", cat: "Santoral", url: "santoral.html?santo=santa-hildegarda", icon: "fa-leaf" },
    { title: "Santa Kateri Tekakwitha", desc: "Patrono de: Ecología, Medio Ambiente y Pueblos Originarios", cat: "Santoral", url: "santoral.html?santo=santa-kateri-tekakwitha", icon: "fa-mountain" },
    { title: "Beato Pino Puglisi", desc: "Patrono de: Paz en los Barrios, contra la Violencia y las Bandas", cat: "Santoral", url: "santoral.html?santo=beato-pino-puglisi", icon: "fa-handshake-simple" },
    { title: "San Miguel Arcángel", desc: "Patrono de: Protección contra el mal, Policías y Seguridad", cat: "Santoral", url: "santoral.html?santo=san-miguel-arcangel", icon: "fa-shield-halved" },
    { title: "El Espíritu Santo", desc: "Patrono de: Fuente de Sabiduría, Ciencia y Entendimiento", cat: "Santoral", url: "santoral.html?santo=espiritu-santo", icon: "fa-dove" },
    { title: "Santa Sofía (Sabiduría Divina)", desc: "Patrono de: Sabiduría, Prudencia y Conocimiento", cat: "Santoral", url: "santoral.html?santo=santa-sofia", icon: "fa-brain" },
    { title: "San Buenaventura", desc: "Patrono de: Teólogos, Filósofos y Doctores del alma", cat: "Santoral", url: "santoral.html?santo=san-buenaventura", icon: "fa-book-sparkles" },
    { title: "Santa Catalina de Siena", desc: "Patrono de: Consejeros, Diálogo y la Búsqueda de la Verdad", cat: "Santoral", url: "santoral.html?santo=santa-catalina-siena", icon: "fa-comments" },
    { title: "San Joaquín", desc: "Patrono de: Abuelos y Padres de Familia", cat: "Santoral", url: "santoral.html?santo=san-joaquin", icon: "fa-person-cane" },
    { title: "Santa Ana", desc: "Patrono de: Abuelas, Madres y Educadoras", cat: "Santoral", url: "santoral.html?santo=santa-ana", icon: "fa-hands-holding-child" },
];
