// Archivo: data-abrazo.js
// Mazo: Abrazo de Dios - 72 reflexiones de consuelo y paz.

const CARTAS_ABRAZO = [
    { id: "abr-01", q: "«Vengan a mí los que están cansados, que yo los aliviaré.»\n\n¿Qué es eso que hoy te pesa tanto que sentís que ya no tenés fuerzas para cargar solo/a?", a: "Mateo 11, 28" },
    { id: "abr-02", q: "«Aunque camine por valles oscuros, nada temo porque Tú estás conmigo.»\n\nEn este momento de oscuridad, ¿podés sentir que Dios no te pide que camines rápido, sino simplemente que te dejes acompañar?", a: "Salmo 23" },
    { id: "abr-03", q: "«No se turbe su corazón ni tengan miedo.»\n\n¿Cuánto de tu angustia actual nace de intentar adivinar un futuro que todavía no llegó, en lugar de descansar en el presente de Dios?", a: "Juan 14, 27" },
    { id: "abr-04", q: "«Sus lágrimas son guardadas en el odre de Dios.»\n\n¿Te permitís llorar frente al Señor, o sentís que tenés que ser 'fuerte' incluso en la oración?", a: "Salmo 56, 8" },
    { id: "abr-05", q: "«Yo estaré con ustedes todos los días hasta el fin del mundo.»\n\nSi realmente creyeras que nunca estás solo/a, ¿qué decisión tomarías hoy con más paz?", a: "Mateo 28, 20" },
    { id: "abr-06", q: "«Mi paz les dejo, mi paz les doy.»\n\n¿Buscás la paz como una ausencia de problemas o como una presencia de Dios en medio del caos?", a: "Juan 14, 27" },
    { id: "abr-07", q: "«Como una madre consuela a su hijo, así los consolaré yo.»\n\n¿Podés verte hoy como un niño/a pequeño/a que simplemente necesita ser abrazado por su Padre del Cielo?", a: "Isaías 66, 13" },
    { id: "abr-08", q: "«Nada te turbe, solo Dios basta.»\n\n¿Qué cosas estás considerando 'indispensables' para tu felicidad que hoy te están robando la tranquilidad?", a: "Santa Teresa de Jesús" },
    { id: "abr-09", q: "«El Señor está cerca de los que tienen el corazón roto.»\n\nEn este pedacito de tu corazón que hoy duele, ¿le dejás lugar a Dios para que entre a sanar?", a: "Salmo 34, 18" },
    { id: "abr-10", q: "«Echa tu carga sobre el Señor y Él te sostendrá.»\n\n¿Estás 'negociando' con tus problemas o realmente se los entregaste a Dios para que Él se haga cargo?", a: "Salmo 55, 22" },
    { id: "abr-11", q: "«Hágase en mí según tu palabra.»\n\n¿Tu resistencia a aceptar lo que estás viviendo hoy es lo que te está causando más sufrimiento?", a: "Virgen María" },
    { id: "abr-12", q: "«Sé de quién me he fiado.»\n\nCuando las personas te fallan, ¿recordás que hay un Amor que es el único que nunca te va a soltar la mano?", a: "San Pablo" },
    { id: "abr-13", q: "«Den gracias en toda ocasión.»\n\nIncluso en este desierto que cruzás, ¿podés encontrar un pequeño detalle de belleza por el cual agradecer hoy?", a: "1 Tesalonicenses 5, 18" },
    { id: "abr-14", q: "«No temas, que yo te he redimido.»\n\n¿De qué culpas pasadas te sigue costando soltarte, cuando Dios ya te perdonó y te llamó por tu nombre?", a: "Isaías 43, 1" },
    { id: "abr-15", q: "«Él sana a los de corazón quebrantado.»\n\n¿Creés que tus heridas son demasiado profundas para la medicina de la Gracia, o te animás a confiar?", a: "Salmo 147, 3" },
    { id: "abr-16", q: "«Su misericordia es nueva cada mañana.»\n\n¿Estás arrastrando el cansancio de ayer, o te permitís empezar este día como una página en blanco?", a: "Lamentaciones 3, 22" },
    { id: "abr-17", q: "«En el silencio se escucha la voz de Dios.»\n\n¿A qué ruido le tenés que bajar el volumen hoy para poder escuchar el susurro de paz del Señor?", a: "San Juan de la Cruz" },
    { id: "abr-18", q: "«Todo lo puedo en Aquel que me fortalece.»\n\n¿Estás intentando sacar fuerzas de tu voluntad o de la oración constante?", a: "Filipenses 4, 13" },
    { id: "abr-19", q: "«Busquen y hallarán, llamen y se les abrirá.»\n\n¿Estás esperando una señal mágica o te estás acercando a Dios con la humildad de quien necesita ayuda?", a: "Mateo 7, 7" },
    { id: "abr-20", q: "«Si Dios cuida de los pájaros, ¿no cuidará de ustedes?»\n\n¿Por qué permitís que la ansiedad económica o material nuble tu confianza en la Providencia?", a: "Mateo 6, 26" },
    { id: "abr-21", q: "«Quédate con nosotros, Señor, que atardece.»\n\nEn este 'atardecer' de tu vida o de tu ánimo, ¿invitás a Jesús a sentarse a tu mesa o lo dejás afuera?", a: "Emaús" },
    { id: "abr-22", q: "«Él conoce cada cabello de tu cabeza.»\n\n¿Sentís que sos 'uno más' en el mundo, o podés saborear que sos un tesoro único para Dios?", a: "Lucas 12, 7" },
    { id: "abr-23", q: "«La paz sea con ustedes.»\n\n¿Qué conflicto familiar o personal necesitás poner hoy bajo la luz de esta bendición de Jesús?", a: "Juan 20, 19" },
    { id: "abr-24", q: "«Ustedes son la luz del mundo.»\n\n¿Tu tristeza está tapando la luz que Dios puso en vos para iluminar a los que te rodean?", a: "Mateo 5, 14" },
    { id: "abr-25", q: "«El amor de Dios ha sido derramado en nuestros corazones.»\n\n¿Cuándo fue la última vez que te detuviste a sentirte simplemente amado/a, sin tener que 'hacer' nada?", a: "Romanos 5, 5" },
    { id: "abr-26", q: "«Bienaventurados los que lloran, porque serán consolados.»\n\n¿Reconocés el valor sagrado de tu dolor actual como un camino de purificación y encuentro?", a: "Las Bienaventuranzas" },
    { id: "abr-27", q: "«Vengan a un lugar solitario y descansen un poco.»\n\n¿Te estás permitiendo el descanso necesario para que tu espíritu se recupere, o vivís en modo alerta?", a: "Marcos 6, 31" },
    { id: "abr-28", q: "«Señor, ¿a quién iremos? Tú tienes palabras de vida eterna.»\n\n¿Estás buscando consuelo en 'cisternas rotas' (vicios, distracciones) o en la Fuente verdadera?", a: "Juan 6, 68" },
    { id: "abr-29", q: "«Bástate mi gracia, porque mi fuerza se muestra en tu debilidad.»\n\n¿Tu fragilidad actual te aleja de Dios o te hace depender más de Su fuerza?", a: "2 Corintios 12, 9" },
    { id: "abr-30", q: "«Miren que yo hago nuevas todas las cosas.»\n\n¿Creés que tu situación no tiene salida, o confiás en que Dios puede sacar brotes verdes de las cenizas?", a: "Apocalipsis 21, 5" },
    { id: "abr-31", q: "«Si el grano de trigo no muere, no da fruto.»\n\n¿Esa pérdida que hoy sufrís podrá ser la semilla de una vida nueva y más profunda mañana?", a: "Juan 12, 24" },
    { id: "abr-32", q: "«Confíen, yo he vencido al mundo.»\n\n¿Le das más poder al 'mundo' y sus problemas que a la victoria definitiva de Cristo?", a: "Juan 16, 33" },
    { id: "abr-33", q: "«Señor, si quieres, puedes sanarme.»\n\n¿Se lo pedís con la fe de quien sabe que para Dios nada es imposible?", a: "El Leproso" },
    { id: "abr-34", q: "«Tú eres precioso a mis ojos y yo te amo.»\n\n¿Podés repetir esta frase mirándote al espejo hoy, sabiendo que es lo que Dios piensa de vos?", a: "Isaías 43, 4" },
    { id: "abr-35", q: "«No se angustien por el mañana.»\n\n¿Cuánta de tu energía de hoy se está yendo en problemas que quizás nunca sucedan?", a: "Mateo 6, 34" },
    { id: "abr-36", q: "«Debajo de sus alas encontrarás refugio.»\n\nCuando te sentís atacado/a por la vida, ¿corres a esconderte en la oración o te quedas a la intemperie?", a: "Salmo 91, 4" },
    { id: "abr-37", q: "«El Señor peleará por ustedes; ustedes manténganse tranquilos.»\n\n¿Estás agotado/a de pelear batallas que no te corresponden, en lugar de dejar que Dios actúe?", a: "Éxodo 14, 14" },
    { id: "abr-38", q: "«Perdónalos, porque no saben lo que hacen.»\n\n¿El rencor hacia alguien te está impidiendo recibir el abrazo de paz que Dios quiere darte?", a: "Jesús en la Cruz" },
    { id: "abr-39", q: "«Mi alma tiene sed de Dios.»\n\n¿Ese vacío que sentís hoy no será en realidad un llamado a profundizar tu vida espiritual?", a: "Salmo 42" },
    { id: "abr-40", q: "«Yo soy el Buen Pastor; conozco a mis ovejas.»\n\n¿Escuchás Su voz en medio del ruido de tus miedos personales?", a: "Juan 10, 14" },
    { id: "abr-41", q: "«Incluso en la vejez, yo seré el mismo.»\n\n¿Te asusta el paso del tiempo o confiás en que el Amor de Dios es lo único que no envejece?", a: "Isaías 46, 4" },
    { id: "abr-42", q: "«El Espíritu acude en ayuda de nuestra debilidad.»\n\nCuando no sabés ni qué pedir, ¿dejás que el Espíritu Santo hable por vos en el silencio?", a: "Romanos 8, 26" },
    { id: "abr-43", q: "«Felices los que tienen hambre y sed de justicia.»\n\n¿Tu indignación por lo que está mal te lleva a la oración o a la amargura?", a: "Mateo 5, 6" },
    { id: "abr-44", q: "«No los dejaré huérfanos.»\n\n¿Actuás como alguien que tiene Padre, o vivís con el desamparo de quien se siente solo en el universo?", a: "Juan 14, 18" },
    { id: "abr-45", q: "«Su nombre es Consejero Admirable, Dios Poderoso.»\n\n¿Buscás primero el consejo de Dios o te perdés en las opiniones de los demás?", a: "Isaías 9, 6" },
    { id: "abr-46", q: "«La alegría del Señor es nuestra fuerza.»\n\n¿Estás esperando que todo esté perfecto para estar alegre, o elegís la alegría como un acto de fe?", a: "Nehemías 8, 10" },
    { id: "abr-47", q: "«El que cree en mí, aunque muera vivirá.»\n\n¿La esperanza de la Vida Eterna ilumina hoy tu forma de enfrentar el duelo o la enfermedad?", a: "Juan 11, 25" },
    { id: "abr-48", q: "«Miren mis manos y mis pies; soy yo mismo.»\n\n¿Reconocés a Jesús en las heridas de tu propia vida y en las de los demás?", a: "Lucas 24, 39" },
    { id: "abr-49", q: "«Yo soy el Camino, la Verdad y la Vida.»\n\n¿Te sentís perdido/a? ¿Y si hoy simplemente te dejás guiar paso a paso por Él?", a: "Juan 14, 6" },
    { id: "abr-50", q: "«Permanezcan en mi amor.»\n\n¿Estás 'visitando' a Dios de vez en cuando o estás 'viviendo' en Su presencia constante?", a: "Juan 15, 9" },
    { id: "abr-51", q: "«Dios es Amor.»\n\nSi esta fuera la única verdad que conocieras, ¿cómo cambiaría tu forma de ver el mundo hoy?", a: "1 Juan 4, 8" },
    { id: "abr-52", q: "«En Ti, Señor, he puesto mi confianza.»\n\n¿Tu confianza tiene 'fecha de vencimiento' o sos capaz de esperar los tiempos de Dios?", a: "Salmo 31" },
    { id: "abr-53", q: "«Pidan y se les dará.»\n\n¿Estás pidiendo con la confianza de un hijo o con la duda de un extraño?", a: "Mateo 7, 7" },
    { id: "abr-54", q: "«El amor echa fuera el temor.»\n\n¿Qué miedo específico necesitás hoy que sea disuelto por el Amor inmenso de Dios?", a: "1 Juan 4, 18" },
    { id: "abr-55", q: "«Tu palabra es una lámpara para mis pasos.»\n\nEn esta confusión que vivís, ¿buscás luz en el Evangelio o en tus propios pensamientos circulares?", a: "Salmo 119, 105" },
    { id: "abr-56", q: "«Alégrate, llena de gracia.»\n\n¿Podés recibir hoy la alegría de Dios como un regalo inmerecido, sin buscar 'excusas' para estar mal?", a: "Ángel Gabriel" },
    { id: "abr-57", q: "«El Señor es mi luz y mi salvación.»\n\n¿De qué tenés miedo si la Luz del universo camina a tu lado?", a: "Salmo 27" },
    { id: "abr-58", q: "«Como el ciervo busca corrientes de agua...»\n\n¿Tu ansiedad no será en realidad una sed profunda de Dios que nada más puede calmar?", a: "Salmo 42" },
    { id: "abr-59", q: "«Señor, ten piedad de mí.»\n\n¿Te permitís ser vulnerable ante Dios y pedirle ayuda de corazón?", a: "Salmo 51" },
    { id: "abr-60", q: "«Ustedes son mis amigos.»\n\n¿Tratás a Jesús como a un juez lejano o como al Amigo que conoce todos tus secretos y aun así te ama?", a: "Juan 15, 14" },
    { id: "abr-61", q: "«El Reino de Dios está entre ustedes.»\n\n¿Estás buscando la paz en un futuro lejano o podés encontrarla hoy en los gestos de amor a tu alrededor?", a: "Lucas 17, 21" },
    { id: "abr-62", q: "«Padre, en tus manos encomiendo mi espíritu.»\n\n¿Podés soltar el control de esa situación que te quita el sueño y ponerla en manos del Padre?", a: "Lucas 23, 46" },
    { id: "abr-63", q: "«Fíate de Dios y haz el bien.»\n\n¿Estás paralizado/a por la duda o te animás a seguir caminando confiando en Su guía?", a: "Salmo 37, 3" },
    { id: "abr-64", q: "«Vengan a desayunar.»\n\n¿Reconocés a Jesús en las cosas cotidianas y sencillas de tu día a día?", a: "Juan 21, 12" },
    { id: "abr-65", q: "«Ámense unos a otros como yo los he amado.»\n\n¿El consuelo que recibís de Dios lo estás guardando para vos o lo compartís con alguien que sufre?", a: "Juan 13, 34" },
    { id: "abr-66", q: "«La esperanza no defrauda.»\n\n¿Tu esperanza está basada en tus planes o en las promesas de Dios?", a: "Romanos 5, 5" },
    { id: "abr-67", q: "«Miren que yo estoy a la puerta y llamo.»\n\n¿Vas a dejar pasar a Jesús a tu vida hoy o lo vas a dejar esperando?", a: "Apocalipsis 3, 20" },
    { id: "abr-68", q: "«Tú eres mi Dios, fuera de Ti no tengo nada.»\n\n¿Qué ídolos o seguridades falsas necesitás soltar para que Dios sea realmente tu todo?", a: "Salmo 16" },
    { id: "abr-69", q: "«Sáname, Señor, y seré sanado.»\n\n¿Le entregás tus heridas más íntimas para que Su luz las transforme?", a: "Jeremías 17, 14" },
    { id: "abr-70", q: "«El Señor te bendiga y te proteja.»\n\n¿Sentís la protección de Dios sobre vos y tu familia en este preciso momento?", a: "Números 6, 24" },
    { id: "abr-71", q: "«Habla, Señor, que tu siervo escucha.»\n\n¿Estás dispuesto/a a hacer silencio para oír lo que Dios quiere decirte hoy?", a: "1 Samuel 3, 9" },
    { id: "abr-72", q: "«Estaré con ustedes siempre.»\n\nSi esta fuera la última carta que leyeras, ¿te irías con la paz de saberte acompañado/a eternamente?", a: "Mateo 28, 20" }
];

const PALABRAS_FONDO = [
    'PAZ', 'CONSUELO', 'ESPERANZA', 'SANTA ANA', 'REFUGIO', 
    'DESCANSO', 'AMOR', 'PADRE', 'ABRAZO', 'FE', 'LUZ', 'CALMA'
];